### ISSUE TITLE
postgres server configuratio

### ISSUE THREAD

**Issue by adderbyte** [chenghonour/formulago#2]
I attempted changing the config file for compatibility with postgres but it constant ly returns SSL not enabled.
I guess this is a general error and it might be due to a number of factors.

Any hint on how to solve this ?

Thank you!

**Comment by chenghonour** [comment]
hello, thank you for your attention, I just updated the code, the configuration will support PostgreSQL, you can try it. If it is convenient, can you star it? Thank you.
